### ISSUE TITLE
konqueror nouveau crash

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk1#11]
Ez is a sötét oldalon áll? (qupzilla, otter)

> kdeinit5: Got EXEC_NEW '/usr/lib/qt5/plugins/kf5/kio/http.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/qt5/plugins/kf5/kio/http.so'
KonqFrame(0x8408878) QObject(0x0)
QUrl("https://github.com/")
QUrl("https://github.com/") type= QWebEnginePage::NavigationType(NavigationTypeTyped)
QUrl("https://github.com/")
[1221:1237:0324/185731.958149:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[1221:1237:0324/185731.958364:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[1221:1237:0324/185731.958507:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: crl4.digicert.com
(pkix_CacheCert_Add: PKIX_PL_HashTable_Add for Certs skipped: entry existed
(pkix_CacheCert_Add: PKIX_PL_HashTable_Add for Certs skipped: entry existed
[1221:1237:0324/185731.960879:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[1221:1237:0324/185731.960989:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[1221:1237:0324/185731.961075:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: crl4.digicert.com
(pkix_CacheCert_Add: PKIX_PL_HashTable_Add for Certs skipped: entry existed
[New Thread 0xc3946b40 (LWP 1295)]
[New Thread 0xc1f81b40 (LWP 1297)]
konqueror: pushbuf.c:727: nouveau_pushbuf_data: Assertion `kref' failed.
>
>Thread 1 "konqueror" received signal SIGABRT, Aborted.
0xf7fd9a62 in _dl_sysinfo_int80 () from /lib/ld-linux.so.2
(gdb) bt
#0  0xf7fd9a62 in _dl_sysinfo_int80 () from /lib/ld-linux.so.2
#1  0xf531ddc0 in raise () from /lib/libc.so.6
#2  0xf531f287 in abort () from /lib/libc.so.6
#3  0xf5316997 in __assert_fail_base () from /lib/libc.so.6
#4  0xf5316a1b in __assert_fail () from /lib/libc.so.6
#5  0xefc46814 in nouveau_pushbuf_data () from /usr/lib/../lib/libdrm_nouveau.so.2
#6  0xefc46755 in nouveau_pushbuf_data () from /usr/lib/../lib/libdrm_nouveau.so.2
#7  0xefc468ae in pushbuf_submit.isra () from /usr/lib/../lib/libdrm_nouveau.so.2
#8  0xefc46b87 in pushbuf_flush () from /usr/lib/../lib/libdrm_nouveau.so.2
#9  0xefc478ca in nouveau_pushbuf_kick () from /usr/lib/../lib/libdrm_nouveau.so.2
#10 0xee1dd03b in nv50_flush () from /usr/lib/dri/nouveau_dri.so
#11 0xedeaee9b in st_context_flush () from /usr/lib/dri/nouveau_dri.so
#12 0xedfaa3e0 in dri_flush () from /usr/lib/dri/nouveau_dri.so
#13 0xf472eff5 in dri2Flush.constprop.4 () from /usr/lib/libGL.so.1
#14 0xf472f3c3 in dri2SwapBuffers () from /usr/lib/libGL.so.1
#15 0xf470674c in glXSwapBuffers () from /usr/lib/libGL.so.1
#16 0xf194b7f0 in ?? () from /usr/lib/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
#17 0xf5e30b08 in QOpenGLContext::swapBuffers(QSurface*) () from /usr/lib/qt5/lib/libQt5Gui.so.5
#18 0xf60dcbec in QPlatformBackingStore::composeAndFlush(QWindow*, QRegion const&, QPoint const&, QPlatformTextureList*, QOpenGLContext*, bool) ()
   from /usr/lib/qt5/lib/libQt5Gui.so.5
#19 0xf189bd96 in ?? () from /usr/lib/qt5/lib/libQt5XcbQpa.so.5
#20 0xf63ecaf3 in ?? () from /usr/lib/qt5/lib/libQt5Widgets.so.5
#21 0xf63ee0a3 in ?? () from /usr/lib/qt5/lib/libQt5Widgets.so.5
#22 0xf63efda8 in ?? () from /usr/lib/qt5/lib/libQt5Widgets.so.5
#23 0xf63efffc in ?? () from /usr/lib/qt5/lib/libQt5Widgets.so.5
#24 0xf640ae81 in QWidgetPrivate::syncBackingStore() () from /usr/lib/qt5/lib/libQt5Widgets.so.5
#25 0xf642382c in QWidget::event(QEvent*) () from /usr/lib/qt5/lib/libQt5Widgets.so.5
#26 0xf6523c5f in QMainWindow::event(QEvent*) () from /usr/lib/qt5/lib/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#27 0xf75e7c07 in KMainWindow::event(QEvent*) () from /usr/lib/libKF5XmlGui.so.5
#28 0xf7627498 in KXmlGuiWindow::event(QEvent*) () from /usr/lib/libKF5XmlGui.so.5
#29 0xf7f00608 in KonqMainWindow::event(QEvent*) () from /usr/lib/libkdeinit5_konqueror.so
#30 0xf63df64a in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/qt5/lib/libQt5Widgets.so.5
#31 0xf63e7176 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/qt5/lib/libQt5Widgets.so.5
#32 0xf5a8a7dc in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/qt5/lib/libQt5Core.so.5
#33 0xf5a8d776 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/qt5/lib/libQt5Core.so.5
#34 0xf5a8dbc7 in QCoreApplication::sendPostedEvents(QObject*, int) () from /usr/lib/qt5/lib/libQt5Core.so.5
#35 0xf5ae4cd3 in ?? () from /usr/lib/qt5/lib/libQt5Core.so.5
#36 0xf230ec59 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#37 0xf230eed9 in g_main_context_iterate.isra () from /usr/lib/libglib-2.0.so.0
#38 0xf230efa4 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#39 0xf5ae4223 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/qt5/lib/libQt5Core.so.5
#40 0xf18dd3e1 in ?? () from /usr/lib/qt5/lib/libQt5XcbQpa.so.5
#41 0xf5a8897d in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/qt5/lib/libQt5Core.so.5
#42 0xf5a91f14 in QCoreApplication::exec() () from /usr/lib/qt5/lib/libQt5Core.so.5
#43 0xf5de9fb1 in QGuiApplication::exec() () from /usr/lib/qt5/lib/libQt5Gui.so.5
#44 0xf63df5a4 in QApplication::exec() () from /usr/lib/qt5/lib/libQt5Widgets.so.5
#45 0xf7f43ff2 in kdemain () from /usr/lib/libkdeinit5_konqueror.so
#46 0x08048887 in ?? ()
#47 0xf530a356 in __libc_start_main () from /lib/libc.so.6
#48 0x080488b5 in _start ()
(gdb)

**Comment by attuska** [comment]
otter-browser működik így:
attila@localhost:~$ export QT_XCB_FORCE_SOFTWARE_OPENGL=1
attila@localhost:~$ otter-browser

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk1/commit/5a379957129950e284a6fa52aede8714cb00520b
