### ISSUE TITLE
gnome-sotware nem működik

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk1#14]
1. nem indult hibás libcanberra split miatt.
2. előbbi kijavítása után meg CSS értelmezési hiba miatt összomlik.
 

> (gdb) r
Starting program: /usr/bin/gnome-software 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0x7fffe3b24700 (LWP 9504)]
[New Thread 0x7fffe3323700 (LWP 9505)]
[New Thread 0x7fffe12be700 (LWP 9506)]
>
>(gnome-software:9500): Gs-ERROR **: CSS parsing error: not a number
>
>Thread 1 "gnome-software" received signal SIGTRAP, Trace/breakpoint trap.
0x00007fffeccd0801 in _g_log_abort () from /usr/lib/../lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007fffeccd0801 in _g_log_abort () from /usr/lib/../lib/libglib-2.0.so.0
#1  0x00007fffeccd17a8 in g_log_default_handler () from /usr/lib/../lib/libglib-2.0.so.0
#2  0x00007fffeccd1994 in g_logv () from /usr/lib/../lib/libglib-2.0.so.0
#3  0x00007fffeccd1b92 in g_log () from /usr/lib/../lib/libglib-2.0.so.0
#4  0x0000000000446e28 in ?? ()
#5  0x00007fffed1aa955 in g_closure_invoke () from /usr/lib/../lib/libgobject-2.0.so.0
#6  0x00007fffed1bc1a2 in signal_emit_unlocked_R () from /usr/lib/../lib/libgobject-2.0.so.0
#7  0x00007fffed1c4d41 in g_signal_emit_valist () from /usr/lib/../lib/libgobject-2.0.so.0
#8  0x00007fffed1c5152 in g_signal_emit () from /usr/lib/../lib/libgobject-2.0.so.0
#9  0x00007ffff53465ce in _gtk_css_parser_error () from /usr/lib/../lib/libgtk-3.so.0
#10 0x00007ffff53471c0 in gtk_css_dimension_value_parse () from /usr/lib/../lib/libgtk-3.so.0
#11 0x00007ffff53547a1 in parse_font () from /usr/lib/../lib/libgtk-3.so.0
#12 0x00007ffff53529da in gtk_css_shorthand_property_parse_value () from /usr/lib/../lib/libgtk-3.so.0
#13 0x00007ffff5349b4f in gtk_css_provider_load_internal () from /usr/lib/../lib/libgtk-3.so.0
#14 0x00007ffff534ae22 in gtk_css_provider_load_from_file () from /usr/lib/../lib/libgtk-3.so.0
#15 0x0000000000446bd3 in ?? ()
#16 0x0000000000446ec4 in ?? ()
#17 0x000000000044733b in ?? ()
#18 0x00007fffed1aa955 in g_closure_invoke () from /usr/lib/../lib/libgobject-2.0.so.0
#19 0x00007fffed1bc59d in signal_emit_unlocked_R () from /usr/lib/../lib/libgobject-2.0.so.0
#20 0x00007fffed1c4d41 in g_signal_emit_valist () from /usr/lib/../lib/libgobject-2.0.so.0
#21 0x00007fffed1c5152 in g_signal_emit () from /usr/lib/../lib/libgobject-2.0.so.0
#22 0x00007fffee5547bd in g_application_real_local_command_line () from /usr/lib/../lib/libgio-2.0.so.0
#23 0x00007fffee5549a2 in g_application_run () from /usr/lib/../lib/libgio-2.0.so.0
#24 0x0000000000417d23 in main ()
(gdb)

**Comment by attuska** [comment]
Szerintem ki kellene dobni, úgysem használható nálunk semmire.

Az appstream cuccot nem fogom én erre a disztribúcióra megcsinálni, sem az apsstream részére egy UBK csomagkészlet adatbázist létrehozni és ráadásul még karban is tartani ennek a programnak a kedvéért. UHU-UBK1 alatt az apt-ot és a synaptic használatosak a szoftverek telepítésére és eltávolítására. Ha egyetértetek ezzel, akkor le is zárhatja ezt az issue -t az, aki törli. Ha nem akkor tessék megcsinálni.

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk1/commit/913f704e89615bd89e0ae7ba64223562dcc86169
Itt kidobva, ubk2 -n még van remény talán, ott valamennyire működik.
