### ISSUE TITLE
xine-ui: Video settings segfault

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk1#20]
A felület Settings/Video menüpontja elszáll. UBK1 és UBK2 esetén is, nvidia és nouveau esetén is.
Az Alt+c gyorsbillentyűre is.

A menüpont használhatatlan.

> attila@attila-pc:~$ gdb --args xine.bin -V xv
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-uhu-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from xine.bin...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/xine.bin -V xv
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
This is xine (X11 gui) - a free video player v0.99.10.
(c) 2000-2014 The xine Team.
[New Thread 0x7fffea2bf700 (LWP 1296)]
[New Thread 0x7fffe9abe700 (LWP 1298)]
[New Thread 0x7fffe92bd700 (LWP 1299)]
[New Thread 0x7fffe8288700 (LWP 1300)]
[New Thread 0x7fffe5630700 (LWP 1301)]
[New Thread 0x7fffe4e2f700 (LWP 1302)]
[New Thread 0x7fffcbc16700 (LWP 1303)]
[New Thread 0x7fffcb415700 (LWP 1304)]
[New Thread 0x7fffcaa11700 (LWP 1305)]
[New Thread 0x7fffca00e700 (LWP 1306)]
[New Thread 0x7fffc980d700 (LWP 1307)]
[New Thread 0x7fffc8c23700 (LWP 1308)]
[New Thread 0x7fffbbfff700 (LWP 1309)]
[New Thread 0x7fffbb7fe700 (LWP 1310)]
[New Thread 0x7fffa17f4700 (LWP 1311)]
[New Thread 0x7fffa0ff3700 (LWP 1312)]
[New Thread 0x7fff9e9a8700 (LWP 1313)]
>
>Thread 1 "xine.bin" received signal SIGSEGV, Segmentation fault.
0x00007ffff59348d6 in __strcmp_ssse3 () from /lib/libc.so.6
(gdb) bt
#0  0x00007ffff59348d6 in __strcmp_ssse3 () from /lib/libc.so.6
#1  0x000000000047327c in ?? ()
#2  0x0000000000474b9a in ?? ()
#3  0x000000000041a223 in ?? ()
#4  0x000000000041d0f7 in ?? ()
#5  0x000000000046d7e6 in ?? ()
#6  0x000000000046b9db in ?? ()
#7  0x000000000047630f in ?? ()
#8  0x000000000047c267 in ?? ()
#9  0x000000000047d8bc in ?? ()
#10 0x000000000047e949 in ?? ()
#11 0x000000000041e75a in ?? ()
#12 0x0000000000411e54 in ?? ()
#13 0x00007ffff582c511 in __libc_start_main () from /lib/libc.so.6
#14 0x0000000000412b8a in ?? ()
(gdb)

**Comment by attuska** [comment]
Csak az alapértelmezett skinnel működik ez a menüpont.
Bármely más letöltöttel már nem működik, valószínűleg skinprobléma. A letölthető skinek nincsenek már régóta karban tartva, ez a xine-ui is már évek óta változatlan, Fedora már ki is hajította.
Nem is lesz kijavítva, lezárom az issue -t.
